# Generated by Django 3.0.5 on 2020-05-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishya', '0003_images2'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
