# Generated by Django 3.0.5 on 2020-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishya', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='addimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
