# Generated by Django 3.0.5 on 2020-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drishya', '0007_adddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('card_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
